### ISSUE TITLE
Scan error 19 on Freestyle Libre 1 sensors

### ISSUE THREAD

**Issue by thanasistrisp** [j-kaltes/Juggluco#10]
At custom rom  (lineage) and nfc working (e.g. with google pay) when I try to scan libre 1 sensor I get error 19. Open libre implementation works.

**Comment by j-kaltes** [comment]
ScanError 19 is caused by an exception. Could you, before you scan, make the following command from you computer?

`adb shell logcat --pid $(adb shell pidof tk.glucodata) > logcat.txt`

When everything goes well, the exception will be logged in logcat.txt.

**Comment by thanasistrisp** [comment]
> ScanError 19 is caused by an exception. Could you, before you scan, make the following command from you computer?
> 
> `adb shell logcat --pid $(adb shell pidof tk.glucodata) > logcat.txt`
> 
> When everything goes well, the exception will be logged in logcat.txt.

Here is the logcat:
[logcat.txt](https://github.com/j-kaltes/Juggluco/files/11000406/logcat.txt)

**Comment by j-kaltes** [comment]
What version of Juggluco do you use?

**Comment by thanasistrisp** [comment]
> What version of Juggluco do you use?

4.10.4 in android 13 (lineageos 20)

**Comment by j-kaltes** [comment]
What happens when you use this one?

https://drive.google.com/file/d/1dmvlpEskw0CI5vdkN40PVg7mTBJuymZD/view?usp=share_link

**Comment by thanasistrisp** [comment]
> What happens when you use this one?
> 
> https://drive.google.com/file/d/1dmvlpEskw0CI5vdkN40PVg7mTBJuymZD/view?usp=share_link

Data processing error... try again
[logcat.txt](https://github.com/j-kaltes/Juggluco/files/11001878/logcat.txt)

**Comment by j-kaltes** [comment]
I leave it so as it is. Previously it did work with Freestyle Libre 1 sensors. I am currently using a Freestyle Libre 3 sensor. Am not going to change anything and risk making it unusable with Freestyle Libre 2 sensors.

**Comment by thanasistrisp** [comment]
> I leave it so as it is. Previously it did work with Freestyle Libre 1 sensors. I am currently using a Freestyle Libre 3 sensor. Am not going to change anything and risk making it unusable with Freestyle Libre 2 sensors.

which app version worked for version 1? Also in readme you say it intends to work for v1...

**Comment by j-kaltes** [comment]
The last Freestyle Libre 1 sensors I used was in April 2021. But I heard of others using Juggluco with Freestyle Libre 1 sensors and I haven't changed this part of Juggluco for a long time.
The oldest I can find is 1.3.5 and that is from November 2021 https://appgallery.huawei.com/app/C104993801
I wouldn't try such an old version.

**Comment by thanasistrisp** [comment]
> The last Freestyle Libre 1 sensors I used was in April 2021. But I heard of others using Juggluco with Freestyle Libre 1 sensors and I haven't changed this part of Juggluco for a long time. The oldest I can find is 1.3.5 and that is from November 2021 https://appgallery.huawei.com/app/C104993801 I wouldn't try such an old version.

so libre1 sensor is end of support? If yes, update readme at home page

**Comment by j-kaltes** [comment]
Yes also Freestyle Libre 3 is end of support and US Freestyle Libre 2, because I mainly use European Freestyle Libre 2 sensors. But I haven't changed anything what should cause these other sensors to stop working.

Don't ask me for support for Freestyle Libre 2 sensors either, support yourself.
