### ISSUE TITLE
Segmentation Fault - juggluco-server

### ISSUE THREAD

**Issue by kfishermail** [j-kaltes/Juggluco#124]
I downoded the following files:
 juggluco-server7.1.10.src.tar.xz
 juggluco-server7.3.0.src.tar.xz
 juggluco-server7.4.0.src.tar.xz
 juggluco-server7.4.3.src.tar.xz

I executed the following steps for each file:
 tar xf jugg*.xz
 cd j*r
 cmake -DDEBUG=on .
 make juggluco
 ./juggluco

versions 7.4.0 and 7.4.3 both gave "Segmentation fault":

  pi@linripper:~/jtest/juggluco-server$ ./juggluco
  Saving in directory jugglucodata
  1707620343 125502 setfilesdir jugglucodata null convfactor=180.182000
  1707620343 125502 initVersion=0
  Segmentation fault

versions 7.1.10 and 7.3.0 seemed to work OK
These are the only versions I tested

I am running Debian:
pi@linripper:~/jtest/juggluco-server$ uname -a
Linux linripper 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux

Any thoughts?  For my usage I will run 7.3.0

**Comment by j-kaltes** [comment]
Thanks for the bug report. I think I have corrected it in version 7.4.4: https://www.juggluco.nl/Juggluco/cmdline/index.html
You probably had this BUG only the first time you ran the program.

**Comment by kfishermail** [comment]
7.4.4 works for me
