### ISSUE TITLE
Phone Unable to Connect to Android Smartwatch (Non-WearOS)

### ISSUE THREAD

**Issue by sidouzi123** [j-kaltes/Juggluco#135]
"Hello, I'm back with another question. 😊 I have a smartwatch with an Android system (not WearOS), and I can't connect this watch's app to my phone's app; the phone app can't see the watch. 🤔

I have an idea: if the mobile app can choose from devices that have already been connected (currently, the phone app can only see WearOS watches, but I hope to see all devices), then can the phone app communicate normally with the watch app? 📱➡️⌚ If not, is it because this communication is based on WearOS? The reason I have this need is that in China's primary and secondary schools, even if you have diabetes, you are not allowed to bring a phone, only a watch, including smartwatches. This sounds absurd, but it's true. 🏫 The reason for not choosing WearOS is that watches with this operating system are very expensive in China, while watches with the Android system are very cheap.  I hope you can help me modify the source code to solve this problem. Thank you very much. 🙏"

**Comment by j-kaltes** [comment]
In the Netherlands smartphones and smartwatches are forbidden in schools (https://www.theguardian.com/world/2023/jul/04/mobile-phones-other-devices-to-be-banned-from-dutch-classrooms), but there is an exception for children that depend on their smartphones for their medical condition, explicitly mentioning diabetics.

The communication between Juggluco on a WearOS watch and Android smartphone makes use of Google Play services for wearable devices: com.google.android.gms.wearable. It needs to be present on both phone and watch. I think that it is possible to [install in on Harmony phones](https://www.whatgear.net/technology/how-to-get-google-on-huawei-2022), but I don’t know if you can install it on Harmony watches.

Non-WearOS watches will have their own way to communicate between phone and watch, but that will be specific for the operating system on the watch. 
It is possible to configure the connection between phone and watch yourself with [Left middle menu→Mirror](https://www.juggluco.nl/Jugglucohelp/connectionoverview.html). See also: https://www.juggluco.nl/Juggluco/mirror/index.html

Also the watch face can only be used with WearOS watches. For that there is no solution. You can only make use of Floating Glucose to display the current glucose value above other watch faces.

**Comment by sidouzi123** [comment]
> In the Netherlands smartphones and smartwatches are forbidden in schools (https://www.theguardian.com/world/2023/jul/04/mobile-phones-other-devices-to-be-banned-from-dutch-classrooms), but there is an exception for children that depend on their smartphones for their medical condition, explicitly mentioning diabetics.
> 
> The communication between Juggluco on a WearOS watch and Android smartphone makes use of Google Play services for wearable devices: com.google.android.gms.wearable. It needs to be present on both phone and watch. I think that it is possible to [install in on Harmony phones](https://www.whatgear.net/technology/how-to-get-google-on-huawei-2022), but I don’t know if you can install it on Harmony watches.
> 
> Non-WearOS watches will have their own way to communicate between phone and watch, but that will be specific for the operating system on the watch. 
> It is possible to configure the connection between phone and watch yourself with [Left middle menu→Mirror](https://www.juggluco.nl/Jugglucohelp/connectionoverview.html). See also: https://www.juggluco.nl/Juggluco/mirror/index.html
> 
> Also the watch face can only be used with WearOS watches. For that there is no solution. You can only make use of Floating Glucose to display the current glucose value above other watch faces.

Hello, I have successfully connected the watch with the sensor through the mirroring function, but I found some other issues during further use. These issues are not related to this topic, so I will move to the discussion area to ask questions. Thank you for your answers to my questions. Thanks again.
