### ISSUE TITLE
Failed run

### ISSUE THREAD

**Issue by ilia53v** [j-kaltes/Juggluco#147]
![Screenshot from 2024-04-11 16-19-18](https://github.com/j-kaltes/Juggluco/assets/56300251/983acd06-4c35-46a2-9137-84d99070b6bf)
Hello. I'm trying to run this application through android studio (on ubuntu), but it crashes with an error. 

FATAL EXCEPTION: main
           Process: tk.glucodata, PID: 20730
           java.lang.UnsatisfiedLinkError: No implementation found for void tk.glucodata.Natives.setlocale(java.lang.String, boolean) (tried Java_tk_glucodata_Natives_setlocale and Java_tk_glucodata_Natives_setlocale__Ljava_lang_String_2Z) - is the library loaded, e.g. System.loadLibrary?

The files indicated in the text are placed in the appropriate folders (all 5 files). 
How can I fix this error?

**Comment by j-kaltes** [comment]
tk.glucodata.Natives.setlocale is in the library compiled in this project.
If you didn't change anything, it should be compiled automatically.

**Comment by ilia53v** [comment]
Thank you. Now everything started fine.
