### ISSUE TITLE
Are libre3 device IDs preserved when uploading?

### ISSUE THREAD

**Issue by jmandel** [j-kaltes/Juggluco#148]
https://github.com/j-kaltes/Juggluco/blob/e4f2c50f722c8c3a49a17ab0409b1a55fba25a5e/Common/src/mobile/java/tk/glucodata/Libreview.java#L104

This code in some circumstances mints a new ID, and I'm wondering if this could be the reason the IDs I see in Libreview CSV download don't match my device serial number. I don't understand the system well, so maybe these aren't even expected to match?

**Comment by j-kaltes** [comment]
These device IDs are always arbitrary numbers used to differentiate between different uploaders. The first time they are generated with the cited procedure and saved. At later times the same number is retrieved. It is useful for knowing which device did the uploading and you can selectively delete the values uploaded by a particular uploader:
![deviceID](https://github.com/j-kaltes/Juggluco/assets/72013079/42842768-eaed-494e-9b54-67f955084dc4)

**Comment by jmandel** [comment]
Ah. Thanks -- I was expecting my device serial number (the one printed on the device and which appears in the juggluco main UI) to appear somewhere in the CSV export from Abbott, but maybe just don't surface that information.

**Comment by j-kaltes** [comment]
In the main user UI of Juggluco the sensor serial number is shown. 
The device ID is specific for a particular app on a particular phone. It stays the same when you switch to a new sensor.
