### ISSUE TITLE
documentation => api response => "stable" response value does not match documentation value

### ISSUE THREAD

**Issue by nigzak** [j-kaltes/Juggluco#150]
Started webserver on Android
called http://MY_IP:17580/x/stream?token=MY_TOKEN

I got the respose line 

```
....	2	19003	142	-0.37	STABLE
```

Looking to the documentation should it not be named "STEADY"?
![image](https://github.com/j-kaltes/Juggluco/assets/102737855/a920fbd0-40e0-470f-a50a-4a75d5afc482)

received: 
![image](https://github.com/j-kaltes/Juggluco/assets/102737855/bc56b668-1e2b-4b49-bfb2-3e6f468a4dfd)

Maybe the documentation is outdated (?)
https://www.juggluco.nl/Juggluco/webserver.html

**Comment by j-kaltes** [comment]
The web server interface always called it "STABLE".  Just another word for the same thing. At other places I call it also "steady":
https://www.juggluco.nl/Juggluco/addwatch.html
https://www.juggluco.nl/Juggluco/glucosebroadcast.html
The table is meant to give meaning to the rate of change parameter in the first column of the table, but using the same label as returned by the web interface is better. I have now corrected it at https://www.juggluco.nl/Juggluco/webserver.html.
