### ISSUE TITLE
Scan Error when trying to first connect to Freestyle Libre 3

### ISSUE THREAD

**Issue by Schabolon** [j-kaltes/Juggluco#151]
Hi,

I just got the Freestyle Libre 3 sensor and wanted to connect to Juggluco.
All permissions were granted and I manually set a Account-ID in the Libreview-Setting.
When I hold my phone close to the Libre 3 sensor, I get the following message: "FreeStyle Libre 3, Scan error, Try again"
(Similar to the last posts in #13 from @Venipa)

Phone Model: Samsung Galaxy S10+
Custom ROM: LineageOs 20 (Android 13)
No Google Play Services -> Official Freestyle Libre App doesn't open
Juggluco Version: 8.0.11

**Comment by j-kaltes** [comment]
Did you try hard enough to scan?

If you have root, you can better hide it for Juggluco and also hide Magisk.

**Comment by Schabolon** [comment]
Thanks a lot for the fast reply.
I tried to scan at least 30 times over the course of 3 hours, and always get the same error message.
My phone is not rooted.

**Comment by j-kaltes** [comment]
You can run a logging version from https://www.juggluco.nl/Juggluco/download.html#bugreport and send trace.log to my email address: jaapkorthalsaltes@gmail.com

**Comment by Schabolon** [comment]
Thanks, I sent the log file.

**Comment by j-kaltes** [comment]
With what app did you activate the sensor with that account ID?
Did you use the sensor with another app or phone or is Juggluco on this phone the first?

**Comment by Schabolon** [comment]
I followed the instructions from https://www.juggluco.nl/Juggluco/libre3/
The instructions said to choose a arbitrary account ID, so these are just numbers I entered manually.
I tried (after failing with my S10+) to use the sensor with my older phone and the Juggluco App, but the device is quite old and the app just crashed after scanning the sensor.

**Comment by j-kaltes** [comment]
What phone was it? With what system ROM? Was it rooted? 
Did scanning succeed?

**Comment by Schabolon** [comment]
The other phone is an Samsung Note 3 with LineageOS 18.1 (Android 11) with root (I forgot it was rooted, so I didn't hide root from Juggluco).
Scanning didn't succeed, the phone kept vibriting for quite some time and nothing happened/the app crashed on different attempts.

**Comment by j-kaltes** [comment]
Android 4.3 (Jelly Bean), upgradable to 4.4.2 (KitKat), upgradable to 5.0 (Lollipop) https://www.gsmarena.com/samsung_galaxy_note_3-5665.php
Maybe it has an old Linux kernel.

But you sensor seems to be activated, so using a somewhat larger account ID will no longer by possible.

**Comment by Schabolon** [comment]
What exactly do you mean by `using a somewhat larger account ID will no longer by possible.`?

**Comment by j-kaltes** [comment]
A sensor that is activated with a particular account ID can only be used with that particular account ID.

**Comment by Schabolon** [comment]
Oh, I see.
So it could be that the "FreeStyle Libre 3, Scan error, Try again" message is due to the fact, that I use the wrong accound ID?

**Comment by j-kaltes** [comment]
No. That is not what I meant. I want to say if the sensor is activated, you can't try another account ID.

**Comment by Schabolon** [comment]
Should I try to get the official FreeStyle Libre 3 App to connect with the sensor, get the Account ID from there and then try to use Juggulco?
Or is that the wrong way?
Sorry, I am a quite confused as what to try next in order to connect with the sensor.

**Comment by j-kaltes** [comment]
What I said also means that you can't use it with the official Freestyle Libre 3 app, because your account ID number doesn't correspond with a Libreview account.
You can try the patched one, because you can there enter the account ID manually. But why should that work when Juggluco doesn't?

**Comment by Schabolon** [comment]
Ok, thanks for the explanation.
So for the future, it would be better to first connect with the FreeStyle Libre 3 app and afterwards use the Jugglo App, just to have the FreeStyle Libre 3 app as a backup option?

Is there anything else that you can think of that I could try to connect to my sensor?

**Comment by j-kaltes** [comment]
No, enter in Juggluco a libreview account and use "Get Account ID" to get an account ID. This can also be used with the Abbott's  Libre 3 app from Google Play.

**Comment by Schabolon** [comment]
I get `postgetauth: status=10 reason=invalidUserOrPassword`
But I can login at https://www.freestylelibre.de/anmelden/login.html with these credentials.

**Comment by Schabolon** [comment]
Aside from the login (which is only relevant for the next sensor, as far as I understand) is there any way to "recover" a connection with my current sensor?

**Comment by j-kaltes** [comment]
Yes without Google Play Services, you get that message. But doesn't it work? Does it show a different Account ID number?
You can also install the gapps under LineageOS.
For example: https://www.pling.com/p/2020746/

**Comment by j-kaltes** [comment]
> I get `postgetauth: status=10 reason=invalidUserOrPassword` But I can login at https://www.freestylelibre.de/anmelden/login.html with these credentials.

I am talking about Libreview.com not www.freestylelibre.de

**Comment by Schabolon** [comment]
> > I get `postgetauth: status=10 reason=invalidUserOrPassword` But I can login at https://www.freestylelibre.de/anmelden/login.html with these credentials.
> 
> I am talking about Libreview.com not [www.freestylelibre.de](http://www.freestylelibre.de)

Oh, that explains it, I'll give it a try, thanks a lot.

**Comment by j-kaltes** [comment]
> Aside from the login (which is only relevant for the next sensor, as far as I understand) is there any way to "recover" a connection with my current sensor?

Try the patched: https://www.juggluco.nl/Juggluco/libre3/patched.html

**Comment by Schabolon** [comment]
When trying to scan the sensor with the patched libre3 app, I get the same error message.

**Comment by j-kaltes** [comment]
The last option is to try it with another phone and when it works, send it via mirror to you current phone and thereafter remove the mirror connection and turn on use Bluetooth.

**Comment by Schabolon** [comment]
Ok, I'll see if thats possible, I currently don't have a third phone at hand.
What would I be sending via mirror?

**Comment by Venipa** [comment]
Ah I fixed it @j-kaltes 
I used a different android phone and transfered it by following the guide on the website, afterwards I was able to scan new sensors directly with the app

**Comment by j-kaltes** [comment]
> Ok, I'll see if thats possible, I currently don't have a third phone at hand. What would I be sending via mirror?

If you want to keep the data on your current phone, you first mirror scans and stream to the other phone, then you reverse the direction of the mirror, sending Scans and Stream from the other phone to this phone. 
Hereafter you scan the sensor with that other phone. After receiving all data on your current phone. You turn off "Sensor via Bluetooth" on that phone and remove the mirror connection and turn on "Sensor via Bluetooth" on your current phone.
https://www.juggluco.nl/Juggluco/mirror/index.html

**Comment by Schabolon** [comment]
Perfect, mirroring from another device finally worked :partying_face: 
Thank you very much for all the help!!
