### ISSUE TITLE
Time sent to libre2patched app interface from juggloco 8.0.20

### ISSUE THREAD

**Issue by Npavkov** [j-kaltes/Juggluco#160]
Does Juggluco receive the bg reading date/time from LIBRE3 sensor to send to patched app interface or does it send the current date/time of the bg reading from on the phone to the interface? started LIBRE3 sensor with juggluco on phone, then use galaxy watch4 as collector of sensor reading, but android wear version of juggluco seems to be sending the galaxy watch 4 collector date/time of the reading?

**Comment by j-kaltes** [comment]
For Juggluco to work correctly, the date and time on all phones and watches that receive glucose values via a mirror connection should be the same. None should be set to the wrong time. Timezone differences don't matter.
The times of the glucose measurements that the sensor sends is relative to the current time. The Juggluco connected to the sensor, transforms that to an absolute time.

**Comment by Npavkov** [comment]
thank you.

**Comment by Npavkov** [comment]
thank you
