### ISSUE TITLE
Cannot build Juggluco due to missing file (timevalues.h).

### ISSUE THREAD

**Issue by shaneharper123** [j-kaltes/Juggluco#161]
`timevalues.h` was missing from the commit for v8.0.18.

The problem still exists with v8.0.22.

I could build Juggluco after creating `Common/src/main/cpp/timevalues.h` with the following contents:
```
#pragma once

#include <stdint.h>

struct timevalues {
    uint16_t warmup;
    uint16_t wear;
};
```

**Comment by j-kaltes** [comment]
The file is now present: https://github.com/j-kaltes/Juggluco/blob/primary/Common/src/main/cpp/timevalues.h
