### ISSUE TITLE
List window: Tapping on an item sometimes opens an edit window for the wrong item.

### ISSUE THREAD

**Issue by shaneharper123** [j-kaltes/Juggluco#165]
Tapping on an item in the List window will open an edit window for the wrong item when the first item displayed doesn't appear at the very top of the left column.

Below is an example of where the first item displayed doesn't appear at the very top of the left column.

![Screenshot_2024-06-01-10-01-23-026_tk glucodata](https://github.com/j-kaltes/Juggluco/assets/139929274/1890c00f-5243-4319-a237-4edd341a5c8b)

I pressed the `<-` button multiple times until my first item was visible. (Pressing the `<- `one more time then results in the first item being displayed at the very top of the left column.)

Tapping on an item opens the edit window for the "following" item when the first item is displayed one position down from the top. (Tapping on the empty space at the top of the left column opens the edit window for the first item.)

The issue could possibly be resolved by ensuring that the first item displayed in the List window always appears at the very top of the left column.

**Comment by j-kaltes** [comment]
I never experienced that the first item was missing. Do you have any idea what caused it?

**Comment by shaneharper123** [comment]
It **always** happens when I go to the first "page" by pressing the `<-` button several times. It does not happen though if I press the `|<` button.

I am running Juggluco v8.0.22.

**Comment by j-kaltes** [comment]
Yes, I can now reproduce it. I will look at it.

**Comment by j-kaltes** [comment]
Does this solve the problem: https://drive.google.com/file/d/1cOIkUcwuhb6rEX_C7fw_-ZzOql7QPBse/view ?

**Comment by shaneharper123** [comment]
> Does this solve the problem: https://drive.google.com/file/d/1cOIkUcwuhb6rEX_C7fw_-ZzOql7QPBse/view ?

Yes. Thank you.

**Comment by shaneharper123** [comment]
Fixed in v8.0.23.
