### ISSUE TITLE
Connectivity guide (ADB)

### ISSUE THREAD

**Issue by ATouhou** [j-kaltes/Juggluco#176]
Hello.
First I would like to thank you for your work :)!
 I just installed your app on a Samsung Galaxy Watch 6.  Connecting through adb was different than the install guide on your website. 
I needed to use the command: "adb pair ip:port pair_code"  rather than adb connect.
I will try to sync the watch with the sensor when my daughter comes home. 
Again, thank you for your work ^^

**Comment by j-kaltes** [comment]
https://www.juggluco.nl/JugglucoWearOS/install/adb.html contains links to https://www.juggluco.nl/JugglucoWearOS/install/WearOS4.0 and that mentions the need for _pair_.
