### ISSUE TITLE
Play alarm sounds using alarm volume

### ISSUE THREAD

**Issue by pborsutzki** [j-kaltes/Juggluco#19]
Hi,

I tried to switch to your app, but immediately found an issue that is a real dealbreaker for me:
My phone is constantly set to vibration regarding the ringtone. Unfortunately Juggluco exclusively plays alarms using the ringtone volume, which means, it never plays the alarms aloud for me. Would it be possible to add an option to switch to a different volume channel, like the alarm one (which is never muted for me)?

I managed to hack this in myself by adding this somewhere [here](https://github.com/j-kaltes/Juggluco/blob/ac84b0e523927409123b04de970a7dc31a2efb12/Common/src/main/java/tk/glucodata/Notify.java#L392
):
```java
ring.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).build());
```
But I would be glad if you could add an option for this to your main branch.

Thanks for developing this app!

**Comment by j-kaltes** [comment]
OK. I have now added USAGE_ALARM. Probably more people will prefer alarm above ringtone.

**Comment by pborsutzki** [comment]
Many thanks for the fast fix!
