### ISSUE TITLE
8.1.6-small notification issue

### ISSUE THREAD

**Issue by KiSa04** [j-kaltes/Juggluco#192]
The notification doesn't show the current value in the new -small version

![imagem](https://github.com/user-attachments/assets/89f3e9d7-7da3-4c54-b5d0-79e0fc87b093)
![imagem](https://github.com/user-attachments/assets/0d0ea510-4455-43f0-978a-a1cdecdb0211)

**Comment by j-kaltes** [comment]
The small version never showed the current value in the notification, neither does the wearOS version. The small version is meant to be used on watches running Android. Putting the current value in the notifications makes little sense for watches. Use another build of Juggluco if you want to the current value in the notification.
