### ISSUE TITLE
missed source layout/notification_action.xml

### ISSUE THREAD

**Issue by MasterPlexus** [j-kaltes/Juggluco#22]
I've got an error message during compiling. Is here maybe a source missed in GitHub?

`Unable to locate resourceFile (/home/dirk/StudioProjects/Juggluco_new/Common/build/intermediates/merged-not-compiled-resources/mobileLibre3/release/layout/notification_action.xml) in source-sets.`

**Comment by j-kaltes** [comment]
As you see in the error message, notification_action.xml is not part of the source of Juggluco. If rebuilding doesn't help, put the source in a new directory or remove some files created by Android studio, for example everything in .idea.

**Comment by MasterPlexus** [comment]
Correct. I clean build, and it become better. not sure what I did in between. Sorry.
