### ISSUE TITLE
Graph is not displayed in the application when using Sibionics

### ISSUE THREAD

**Issue by KytGluc** [j-kaltes/Juggluco#224]
Connected the Sibionics sensor (application version 8.2.9). The sensor is connected, the current glucose value is displayed on the screen, but there is no graph. At the same time, if you send the stream for the time worked - all measurements are in the file.

**Comment by j-kaltes** [comment]
Is right middle menu->Stream[x] checked?

**Comment by KytGluc** [comment]
Thank you. It's working!
