### ISSUE TITLE
Getting data in the Libre 3 app simultaneously after installing Juggluco

### ISSUE THREAD

**Issue by sshivaji** [j-kaltes/Juggluco#28]
I want to recommend this app to others, however, some people still want output in Abbot's libre 3 app. I am unable to get output on Abbot's apps and Juggluco simultaneously. Is there a way to do this?

Thanks a lot for the juggluco app. I was diabetic and no longer am, thanks in part to this app. The analytics helped a lot in debugging my blood sugar spikes, lowering my average sugar and much more! You deserve a standing ovation.

**Comment by MrGutis** [comment]
There's an patched libre 3 app (14 days version) which has embedded Jugglucco version. You can setup it to act as source and then separately Jugglucco app as an receiver. You can search for "Libre 3 mit Patched App" and find the document with instructions how to set it up.  You'll see the readings in both apps

**Comment by sshivaji** [comment]
Thanks a lot! I tried the libre 3 patched app, but when clicking on patched libre broadcast, it says no app listening to librelink. Thus, I cannot send back from juggluco to libre.

Maybe the only way is to make patched libre as the source, and to rescan my sensor and Jugglucco as a receiver. I don't want to do this now as Jugglucco is a billion times better. However, a relative wants to use this app, I will recommend this approach. If this works for someone, I can close the issue. Thanks again.

**Comment by j-kaltes** [comment]
When one searches for _patched libre 3 app_ one finds sites like https://www.etsy.com/listing/1108840882/freestyle-libre-3-patch-waterproof and https://www.juggluco.nl/Juggluco/libre3/patched.html.
But for what would one need the Libre 3 app? One can also switch back and force between Juggluco and the Libre 3 app. Libre 3 sensors saves the 5 minutes (history) values from the start of the sensors and the 1 minutes values of the past 2 hours, and these are send over to the app after it was disconnected for some time.
When there are long lasting sensor errors, you can switch to the Libre 3 app to get the right error message needed for Abbott's customer service.
You should force close the app not in use to prevent interference.

**Comment by sshivaji** [comment]
Thanks for the info. I don't need the Libre 3 app personally at this point. However, when persuading others to switch to Juggluco, it's good to have the Libre 3 app as an option. Maybe switching back and forth might be easier for new users. I found the every minute value of Juggluco to be more useful than the average of the last 5 minutes (?) value from Libre 3.

**Comment by sshivaji** [comment]
The most reliable solution for tech users is just to uninstall the libre 3 app after you get the libreview.com (or app) credentials. Then we don't have to worry about bluetooth disturbances. For NON-tech users, I don't know what the best solution is as the installation itself is difficult and the provided patched libre 3 does not work on every region. I will open a separate issue for helping non-tech users.
