### ISSUE TITLE
Ability to put in notes for a particular time of the day

### ISSUE THREAD

**Issue by sshivaji** [j-kaltes/Juggluco#29]
I see that we have the ability to put in numbers on any point in the graph followed by activities. However, if you see below, we are restricted to numbers and 6 activities. Can we allow free-form text such as "large apple", "cafe latte" or "boarding a flight"? This makes it easier to search for these events in the log and see how your body reacted.

![image](https://github.com/j-kaltes/Juggluco/assets/1430554/10929c20-55bb-40e2-92f6-aa4aee717637)

**Comment by sshivaji** [comment]
Looks like you can add labels for large apple or cafe latte, or food labels, the only thing missing might be a custom event. I guess we can always play with labels and get a behavior similar to what we need.

**Comment by j-kaltes** [comment]
You can specify up to 40 labels.  Under the label for carbohydrate, you can also specify a meal out of its components:
![meal](https://github.com/j-kaltes/Juggluco/assets/72013079/1b6b08d5-07c7-4988-84cd-d69c6fbaa82e)

**Comment by sshivaji** [comment]
Wow, thats good enough! I will add in custom labels like "light exercise", "in flight" etc. How did you change your app language to Portuguese, as it's probably not your phone's language? :)

**Comment by j-kaltes** [comment]
You can change the phone language in Android settings configuração do sistema -> idioma a região.
Labels you can set in Juggluco Left menu->Definições->Etiquetas numéricas.

**Comment by sshivaji** [comment]
I appreciate you changing your whole android system language to Portuguese
to explain! I thought there was a way to change language within Juggluco
itself.

I understood the method to add labels. Will try creating and testing labels
for my use cases. Thanks!

**Comment by sshivaji** [comment]
The label solution works well, closing issue to clean up the tracker.
