### ISSUE TITLE
slog.h is missed during compiling

### ISSUE THREAD

**Issue by MasterPlexus** [j-kaltes/Juggluco#30]
Hi. did you you include a new library? I get the message 
`/home/dirk/StudioProjects/Juggluco_new/Common/src/main/cpp/debugclone.cpp:119:10: fatal error: 'slog.h' file not found`
during compiling.

**Comment by j-kaltes** [comment]
That is no library; it is just a header file I made and I forgot to add to the git. Now it should be present.

**Comment by MasterPlexus** [comment]
got it. Thanks

**Comment by MasterPlexus** [comment]
It looks like something in addition is missed?

`import nodomain.freeyourgadget.gadgetbridge.model.WeatherSpec;`

looks like not part of the git...

**Comment by j-kaltes** [comment]
I have now also added that class.

**Comment by MasterPlexus** [comment]
it works.
