### ISSUE TITLE
Nightscout laptop/desktop sync does not work when moving physical locations

### ISSUE THREAD

**Issue by sshivaji** [j-kaltes/Juggluco#34]
This works perfectly for me when I am on home WIFI. However, when I go to work or am at a cafe, nightscout sync to my laptop stops as the IP address of my phone has changed. What is the best recommended setup? Ideally, it would be great to see my current glucose value on my laptop without looking at my phone or watch :) Can we use the name of the phone or is there a way to connect via bluetooth sync, I don't think this is possible for nightscout is it?

<img width="818" alt="image" src="https://github.com/j-kaltes/Juggluco/assets/1430554/bb9bf89a-4a16-4457-aa1d-784c618f760f">

<img width="256" alt="image" src="https://github.com/j-kaltes/Juggluco/assets/1430554/aae0f635-aac4-49a0-8ac0-523525f72c6d">

**Comment by j-kaltes** [comment]
If you also have your phone with you, you can turn on a portable hotspot on your phone or laptop. It can be difficult to configure it in such a way that it doesn't use a different IP every time it is turned on.
When connected via a portable hotspot, it is also possible to run a Android emulator with Juggluco on your laptop and connect laptop and phone with a mirror connection.

**Comment by sshivaji** [comment]
Good point. I was hoping for a name for my phone, just like we have raspberrypi-local for any raspberry pi on the same network. I suspect this is phone dependent. Will add to this issue if I can get a working config for my phone.
