### ISSUE TITLE
App crashes when moving time

### ISSUE THREAD

**Issue by LuisPuertollano** [j-kaltes/Juggluco#36]
Hello,

App crashes when trying to move left (into the past) or right (into the future or to see sensor number). See attached video.

https://github.com/j-kaltes/Juggluco/assets/77344100/166de036-a2fd-4c0a-a425-656a84c3d18b

I'm logged into libreview, receiving data locally from the patched libre3app, and data updates regularly without problems in juggluco...just trying to look into the past or future causes the app to crash. 
Despite the crashes, data is forwarded without delay to xdrip and thrn aaps, so I have to guess there is something in the graphics going on.

Help please? 😇

This keeps happening:
In Android 12 and 13
In Juggluco version 4.13.x, 4.17.x and 4.18.0 (latest)

I guess something is off in my phone, but i don't know what exactly.
![Screenshot_20230529_195105_Juggluco](https://github.com/j-kaltes/Juggluco/assets/77344100/da577872-50eb-415f-9e94-7ad54ddd82b8)
![Screenshot_20230529_195115_Juggluco](https://github.com/j-kaltes/Juggluco/assets/77344100/ea8e3e0d-cd73-43b7-8770-289a7cc8bb65)
![Screenshot_20230529_195120_Juggluco](https://github.com/j-kaltes/Juggluco/assets/77344100/1ba631eb-b6fc-459d-b7fe-a86a68588109)
![Screenshot_20230529_195133_Juggluco](https://github.com/j-kaltes/Juggluco/assets/77344100/41c76ede-750f-4c93-b481-a29b40910d57)
![Screenshot_20230529_195145_Juggluco](https://github.com/j-kaltes/Juggluco/assets/77344100/51a856b0-d276-4c4d-9b39-85c5aaa67f46)

I can open the search by date option, but when i click on a selected date, the app crashes "softly". As said before...data keeps beeing forwarded and loop doesn't open.

Thanks in advance! 
BR

**Comment by j-kaltes** [comment]
You get that kind of problems when not all data is available in Juggluco because you reuse an old mirror connection in the patched libre 3 app. 
The libre 3 app thinks that all data before a certain point are available, but by using an old connection for a Juggluco that doesn't have this data this is not true.
This can be solved by pressing resend data for this connection in the patched Libre 3 app.
Probably you are also using on old patch of the libre 3 app.

**Comment by LuisPuertollano** [comment]
This means, dhould I delete the Libre 3 app and take over the connection with juggluco (as I'mlogged in libreview), I should be able kill 2 birds with 1 stone?

**Comment by j-kaltes** [comment]
I didn't say that. You could do that, but you don't need to.
If you want to keep to your current configuration, you should press "Resend data" in the Libre 3 app.
But you are right, connecting Juggluco directly with the sensor is the best option.
EDIT:
but before you do that, you should also press "Resend data" in the Libre 3 app.
If you keep with the patched Libre3 app, you can better update to a newer patch:
https://www.juggluco.nl/Juggluco/libre3/patched.html

**Comment by LuisPuertollano** [comment]
Ok, "Resend Data" solved the problem, thank you! I´m also wanting to have the less apps the best,..for the sake of simplicity...and the last(s) version(s) of juggluco added the possibility to have a 2nd sensor in parallel for the warm-up period...thats just great :-)
Anyway, thank you again!
