### ISSUE TITLE
Custom triggers/alerts for fast rising blood sugar beyond 170 or a custom value

### ISSUE THREAD

**Issue by sshivaji** [j-kaltes/Juggluco#37]
Is there a way to program an alert such as your blood sugar is rising fast beyond 170? I am curious if a text notification is possible via an event or what the other options are. I note that there is a feature to send notifications via the Juggluco app. I could potentially use an android app automator and turn this value on with certain rules. However, I wonder what the best way to do this is.

**Comment by j-kaltes** [comment]
Juggluco itself doesn't have a fast rising alarm. One could in principle write an android app, that listens to a glucose broadcast, to generates these kinds of alarms.

**Comment by sshivaji** [comment]
Is the best way to listen to the nightscout broadcast? I guess the
alternative is to have an alarm on a value like 160 or something and maybe
leverage the android notification capability that Juggluco has.

**Comment by j-kaltes** [comment]
https://www.juggluco.nl/Juggluco/glucosebroadcast.html

**Comment by sshivaji** [comment]
Thanks, that will work!
