### ISSUE TITLE
scan error on sensor change

### ISSUE THREAD

**Issue by Npavkov** [j-kaltes/Juggluco#41]
I changed to a new libre2 sensor and it scans reliably in libre2 app, but juggluco always gets a scan error (18). What does scan error 18 mean. is there a trick to getting the sensor into juggloco without scanning?

**Comment by j-kaltes** [comment]
From what country is the Libre2 sensor?

**Comment by Npavkov** [comment]
I believe it is US. Is there a way to tell?

**Comment by j-kaltes** [comment]
On the box there is text in English and Spanish and it includes also an alcohol wipe. https://myehcs.com/product/freestyle-libre-2-sensor/
Today yesterday and today,  I received a lot of posts of users who can't scan **new** US Freestyle Libre 2 sensors with Juggluco. Can you use the patched Libre 2 app? https://www.juggluco.nl/USLibre2

**Comment by Npavkov** [comment]
did Abbott change the sensors in US to cause juggluco to not scn them anymore ? if not what did change. I had successfully had the last 4 sensors were scannable by juggluco?

**Comment by j-kaltes** [comment]
Do you know the date on the last sensor and the last four sensors?
The dates of the sensors of two people with problems are: 2023-12-31 and 2023-11-03

**Comment by Npavkov** [comment]
2023-12-31

**Comment by j-kaltes** [comment]
Is that the date of the bad sensor? Do you know the dates of the good sensors?

**Comment by Npavkov** [comment]
I do notice on the top of the box, it does contain english and spanish on it, but no alcohol wipe in the box?

**Comment by Npavkov** [comment]
the good sensors are dated 2023-10-31. they also had english and spanish on top the box.

**Comment by j-kaltes** [comment]
https://www.totaldiabetessupply.com/products/freestyle-libre-2-sensor-14-day
Here you can read: 
_FreeStyle Libre 2 Sensor Kit Includes:
Sensor
Sensor applicator
(2) Alcohol wipes
Product information card
Reader not included_

**Comment by Npavkov** [comment]
the boxes for the new sensors look EXACTLY the same as old sensors.

**Comment by Npavkov** [comment]
I have a collection of my old sensors (even a few that have feel off) and they all report data processing error and scan error 18 on the new version of juggluco. I not sure if that is notable or not.

**Comment by Npavkov** [comment]
if I use the libre2 patch in this post, will the sensor still send data every minute to juggluco?

**Comment by Npavkov** [comment]
I am unable to get the patch in this post to work on my phone, when I try to scan the sensor with it , it just hangs my phone and I have to restart......

**Comment by j-kaltes** [comment]
"_Data processing Error_" is what one always gets with old sensors and "_Try again Scan Error(18)_" will happen now and then. The patched us Libre 2 app doesn't hang phones and will send every minute a glucose value to Juggluco.

**Comment by Npavkov** [comment]
I will try again the patch.....

**Comment by Npavkov** [comment]
ok, tried the new patch again. Let me ask you a question..... what do you call it when the patch app says "apply the sensor", then "scan the sensor"..... and when I scan it vibrates and makes the NFC sound and afterwards the app does not show any acknowledgement of the scan, and the "back button" and I get a message on my phone "libre2 is not responding"?

**Comment by j-kaltes** [comment]
You mean that Android gives a  _Libre2 is not responding_ message?

**Comment by Npavkov** [comment]
yes!!

**Comment by j-kaltes** [comment]
The app itself hangs. So you only have to kill it. 
I just scanned a European sensor with it and it worked. Sometimes it also doesn't respond at all, but after a few attempts it works.

**Comment by j-kaltes** [comment]
> I do notice on the top of the box, it does contain english and spanish on it, but no alcohol wipe in the box?

Also on the box of British sensors is text in English and Spanish: https://www.britishchemist.co.uk/product/freestyle-libre-2-sensor/

**Comment by Npavkov** [comment]
ok, I have tried the patch scan>terminate cycle more than 6 times and still nothing. Patch still not responding and no data in juggluco? I am not so sure the sensor I have is European..I think it is US.

**Comment by j-kaltes** [comment]
It is strange that it hangs after the scan. Do you have a very slow phone or what? I never have to terminate it after a scan. Did you install https://apkfab.com/libre-2/test.freestylelibre2.us/apk?h=c23a18f939207ee342d2054c551274f1b91c69a87f9691ac78f94eb49bc4a056
?
Even when I scan an old sensor it works: It gives a "Sensor Ended" message.

**Comment by Npavkov** [comment]
I have no issue with the normal libre2 app scanning the sensor-AT ALL!!  My phone is not what I would consider SLOW- I have A LG V30 phone.

**Comment by Npavkov** [comment]
yes that is the patch (link) that I installed on my phone.

**Comment by Npavkov** [comment]
any other thoughts or ideas?

**Comment by j-kaltes** [comment]
Yes, maybe you could run a logging version of Juggluco and return the log file to me after you have tried to scan a few times.
https://drive.google.com/file/d/1a2p8ZRWyFcLHQHIz_BAEkAJlWKryqYss/view?usp=drive_link
You can get the log file out of your phone with:
`adb shell run-as tk.glucodata cat /data/data/tk.glucodata/files/logs/trace.log > trace.log`
and then Email trace.log to me.
After you have reinstalled the non-logging version, you can remove this log file with:
`adb shell run-as tk.glucodata rm /data/data/tk.glucodata/files/logs/trace.log`

**Comment by Npavkov** [comment]
I am not familiar with this....where do I enter this command?  on my computer or the phone?

**Comment by Npavkov** [comment]
Hope this log helps….Let me know what you find…. Thanks for your help.

**Comment by j-kaltes** [comment]
Where is the log? You can email it to jaapkorthalsaltes@gmail.com

**Comment by Npavkov** [comment]
sorry sent it to reply of your email..... I just sent it to  the email you referenced....Thanks

**Comment by Npavkov** [comment]
Hi, did you receive the log I sent to you? was it helpful?

**Comment by j-kaltes** [comment]
Didn't you receive my e-mail in answer on your e-mail with the log file?
I could find where it went wrong, but don't have enough information to do something about it.
You seem to have US Libre 2 sensors. Was the device Aaddress of previous sensors colored red in Left menu->Sensor?

**Comment by Npavkov** [comment]
Thanks for responding…..in answer to your question…..NO, there is no sensor listed under LeftMenu>”sensors”…. I was never able to scan it via nfc in Juggluco to get it to startup the sensor. I initially scanned the sensor in libre2 app and it started up fine, I was then attempting to scan in juggluco to start the sensor in juggluco. It fails all scans in juggluco.

 

If I can offer any other help to you to resolve this I am more than willing to try…..

**Comment by Npavkov** [comment]
Something that might be of help, is when I scan it in libre2 app, it buzzes normally once then makes a different sound and successfully scans.

**Comment by j-kaltes** [comment]
Do you use https://play.google.com/store/apps/details?id=com.freestylelibre2.app.us ?
Then you know that it is a US Libre 2 sensor.
I found somewhere the apks on the internet, but I am uncertain if they are the right ones. Can you give me the APKS from your device?
One can find their names with:
`adb shell pm path com.freestylelibre2.app.us`
Thereafter you can pull the files from your phone one by one with
`adb pull `_FILENAME_
For example when `adb shell pm path com.freestylelibre2.app.us` returns:
```
package:/data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/base.apk
package:/data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/split_config.arm64_v8a.apk
package:/data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/split_config.xxhdpi.apk
```
One pull these three files (output minus _package:_) from the device, one by one, with:
```
adb pull /data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/base.apk
adb pull /data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/split_config.arm64_v8a.apk
adb pull /data/app/~~VPhFIm1p52GtVTRweCTdWQ==/com.freestylelibre2.app.us-IULLEQmXzFzLozvm62O_Sg==/split_config.xxhdpi.apk
```

**Comment by Npavkov** [comment]
Files sent to your gmail acct.

**Comment by j-kaltes** [comment]
I didn't receive you e-mail. Can't you put the apks on google drive and make it public or so and give me the urls?

You can try out a version of Juggluco that just ignores the error. You never know:
Log version: https://drive.google.com/file/d/1xCX8T2KJHyYFVDvuHHbMU8Y7y72iT1wb/view?usp=drive_link
Non logging version: https://drive.google.com/file/d/1dsVhHftzJDRKFAGkkz6efI1fatkCdCqd/view?usp=drive_link

**Comment by Npavkov** [comment]
Still get scan error with ignore release….now I get error 19

**Comment by Npavkov** [comment]
check your gmail acct again, I resent them unzipped.

**Comment by Npavkov** [comment]
did you get the files that time?

**Comment by j-kaltes** [comment]
No, I didn't. I received an e-mail without attachments.

**Comment by Npavkov** [comment]
Ok, I never used google drive, how do I do that?

**Comment by Npavkov** [comment]
is there a way you could modify Jugglco to allow MANUAL entry of sensor info in place of NFCC scan to start it in Juggluco?

**Comment by j-kaltes** [comment]
You can't know what information you have to enter, without scanning the sensor. 

Uploading to google drive is not so difficult:
- go to https://drive.google.com with your gmail address and password. 
- open the _My Drive_ folder.
- Press the right mouse button and select "file upload"
- Select the APK'S and press Open or so
- After the files are uploaded select them and press the right mouse button and select "Share"
- Under general access, select "Everyone with a link" and press done
- Hereafter select each individual apk in turn and press the right mouse button and select "Copy link" and past this link in the message you send.

**Comment by Npavkov** [comment]
https://drive.google.com/file/d/1b3YqLlc7T82TEgxzShStmBFuSXScKYAx/view?usp=sharing

https://drive.google.com/file/d/17Juod4TbXuHvlCzfxHEqyAeHJvHxgZeA/view?usp=sharing

https://drive.google.com/file/d/1i-UGQR1jtlONhGtJwUGfnVD6kIfku2ag/view?usp=sharing

 

Thanks for your help

**Comment by j-kaltes** [comment]
Thanks, 
The files are identical to those I found at apkaio.com, except that you have split_config.xxxhdpi.apk and at apkaio it is xxhdpi, a smaller screen resolution.

**Comment by Npavkov** [comment]
can I fix it to work?

**Comment by Npavkov** [comment]
I am confused. I initially had a WORKING version of Juggluco (working for 5-6 sensors) without issues UNTIL I switched to this sensor and was not able to scan it in the version I had. I tried to update the juggluco to current version and that ALSO did not help. I am convinced that ABBOTT must have changed the NFC tag for this sensor causing it to have issues scanning in other apps. However there is no way to be sure. Does the nfc tag of the sensor look ok in juggluco scan in the log?
II have verified that the sensor ALSO does not scan in DIABOX.

**Comment by j-kaltes** [comment]
There is a lot of data send via NFC and one test gave an error. Something is changed. You can install and run the unpatched US Libre 2 app https://drive.google.com/file/d/1vPS3djE7m3THbhhQfmsARCvgHGBagGxe/view?usp=drive_link
When that one doesn't work with the new sensors, the sensors are certainly different.
You can contact Abbott customer service with it.
A problem is that the unpatched US Libre 2 app will only scan sensors that it activated. I don't know how it is when you use the same Libreview account that activated the sensor.
By uninstalling the original app, you run the risk of rendering the sensor unusable.
You can later update to the current version without problem.

**Comment by Npavkov** [comment]
I do not use an UNPATCHED version of libre2 APP. It is the stock version. I only use the APP  to startup the sensors in the past. As I said before the sensor is scanning perfectly in the libre2 APP, and started successfully. I still think something has changed however with the sensor. Did the log I sent earlier show a valid scan of the sensor?

**Comment by j-kaltes** [comment]
The unpatched version is the stock version. Because you and others claim that the sensors don't work with the patched US Libre 2 app version 2.7.1, the app is also changed. To be certain, someone need to try out the stock US Libre 2 app version 2.7.1 and contact Abbott Customer service.

**Comment by Npavkov** [comment]
my phone shows it is using the libre2 app version 2.7.2 that was installed from google play store. Like I said this version was working for multiple sensors in the past and CONTINUES to work NOW. It scans perfectly with no errors.
The app has not changed between the last sensor that was working. ABBOTT will most likely say that the sensor is working as expected.

**Comment by j-kaltes** [comment]
Yes, and if 2.7.1 doesn't work with the new sensors, 2.7.2 changed something important to be able to connect to changed sensors.

**Comment by Npavkov** [comment]
why would I use 2.71 when I have been using 2.7.2 all along (many sensors that juggluco was able to scan in the past!)

**Comment by j-kaltes** [comment]
Because it is expected not to work.

**Comment by Npavkov** [comment]
the apk from the link above:
You can install and run the unpatched US Libre 2 app https://drive.google.com/file/d/1vPS3djE7m3THbhhQfmsARCvgHGBagGxe/view?usp=drive_link

reports the file is a invalid format?

**Comment by j-kaltes** [comment]
You should not just install it because of what I said before. But to install it you go to an empty directory and unzip the file:
`unzip "FreeStyle Libre 2 US_v2.7.1_apkpure.com.xapk"`
Then do:
`adb install-multiple -r *.apk`
You will receive the message:
adb: failed to finalize session
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
Because you have still your previous version installed. Don't uninstall it because of the reasons I mentioned previously.

**Comment by Npavkov** [comment]
I can not get the adb commands to work
![Screen Shot 06-13-23 at 11 28 AM](https://github.com/j-kaltes/Juggluco/assets/130666275/cb03c822-d4cb-4d55-84dc-7d473001de63)

**Comment by Npavkov** [comment]
ok, using new sensor....version 2.7.1 will not scan the sensor...multiple scan attempts multiple errors. Abbott must have changed something within the nfc tag or the sensor that is not allowing other apps to scan the sensor!!!
Sorry, but I guess that means that Abbott has just disabled juggluco with libre2 sensors....&^%$#@#$%^&

**Comment by Npavkov** [comment]
is there anything you can do to make this work in juggluco?

**Comment by Npavkov** [comment]
Just got this this morning from Abbott:


 Dear Valued Customer,

The LibreLinkUp app* will be updated to version 4.7 on June 14, 2023. This means your current version of the app will no longer be supported and will not receive glucose data from your connections starting June 21, 2023. Please download the latest version to continue receiving glucose data from your connections.

**Comment by Npavkov** [comment]
Do you think you will be able to get the changed libre2 US sensors to work with Juggluco again? I hope so I really like the Juggluco app to track my bg.

**Comment by j-kaltes** [comment]
Why not? I also managed to do it with EU Libre 2 sensors, the previous version of US Libre 2 sensors and Libre 3 sensors. Someone in the USA has already sent me an US sensor and when that arrives I can find out what makes them different. For the previous US Libre 2 sensors, one sensor was enough.

**Comment by Npavkov** [comment]
That is great news. I do not want to give up the convenience of juggluco. I will be anxiously awaiting news on this update. Please let me know.....Thank you.

**Comment by Npavkov** [comment]
any luck in getting the modified libre2 sensors to scan in juggluco?  do you have any kind of ETA?

**Comment by j-kaltes** [comment]
As a temporary solution I have made a patch of the US Libre 2.7.2 app that can send glucose values to Juggluco.
Making the connection between the patched US Libre 2.7.2 app and Juggluco is done in the same way as with the Patch Libre 3 app, see: https://www.juggluco.nl/Juggluco/libre3/patched.html
You don't need to uninstall the original US Libre 2 app, but it should be forced stopped to prevent it from interfering with the connection. You can use it with you current sensor; the sensor doesn't need to be started with this app.
It will overwrite the data allready present in Juggluco. To prevent this, you have to first send the data in Juggluco to the patched US Libre 2.7.2 app and before reversing the direction.

Tell me whether is works or not.

EDIT:
See: https://www.juggluco.nl/USLibre2

**Comment by Npavkov** [comment]
Your temp solution worked fine. Thank you for providing this fix and getting the libre2 sensors usable in juggluco again. 
However, I am now having issues getting my Sony sw3 to connect to USb to sideload google play services via ADB, do you have any ideas you can offer me here?

**Comment by j-kaltes** [comment]
https://androidaps.readthedocs.io/nl/latest/Usage/SonySW3.html

Maybe this version of Juggluco does work with new US Libre 2 sensors:
https://drive.google.com/file/d/1hrrYsiLnnfLSRwcrMxrTy3QbLmjPolvR/view?usp=drive_link

**Comment by Npavkov** [comment]
I was unable to download juggluco5.0.0 version you referenced. It says the file is in your garbage folder and will not let me get to it.

**Comment by j-kaltes** [comment]
I saw that I had to make some more modifications so I deleted it and also the post you was still able to read. I hope nobody has tried it.
I have now uploaded a new one: 
https://drive.google.com/file/d/1UgGuwDXb_OJMRDWMrYQ_m56VaEOY29Ec/view?usp=drive_link

**Comment by Npavkov** [comment]
That version still gives me scan error 18…….any ideas?

**Comment by j-kaltes** [comment]
Juggluco 5.0.0 for arm64 works with new US Libre 2 sensors:
https://www.juggluco.nl/Juggluco/download.html
Does it also work with old US Libre 2 sensors?

**Comment by seliestel** [comment]
Hi, I have a very similar problem as the OP, but with a European Libre 2 sensor. The sensor is part of a batch which I had been using without any issues for a couple of months. Yesterday, when my previous sensor expired, I put on this new one. I scanned it twice with the Juggluco phone app as usual, waited for 60 minutes, and it was scanning values for some time. However, the Bluetooth, after the first handshake, was never operational (Last Success value was empty). I tried disconnecting/connecting Bluetooth and phone several times, but could not make it to work. After a few hours, the NFC scanning function also broke down. Now, NFC scans give a "Data processing error" message. I haven't been able to scan values for the last 12 hours. My sensor is dated 30-4-2023. Is there any solution for this? Thank you for your help.

**Comment by j-kaltes** [comment]
The last remark (of seliestel) has absolutely no  relation with this issue and should be handled in a separate issue.

**Comment by seliestel** [comment]
> The last remark (of seliestel) has absolutely no relation with this issue and should be handled in a separate issue.

OK. Not quite sure if it is "absolutely" unrelated. But I have opened a new issue.

**Comment by j-kaltes** [comment]
The only relation is that you can try out the patched US Libre 2.7.2 app, to see what error message you get there.
https://www.juggluco.nl/USLibre2

**Comment by rahlquist** [comment]
Activated new sensor this morning. Had not been using one for a few weeks. Getting error 18 when scanning 
Version Code: 410
Version Name: 5.1.5
arm64-v8a
Build time: 06:31:09 18-Jul-2023
Libre app 2.7.2.7077
Suggestions on troubleshooting?
Edit: Sensor info. Should be a US sensor, no alcohol pads have come in mine for months. Dual language English/Spanish package showing source of Alameda, CA. Let me know if you need more info. 
Happens on Android 11 (OnePlus 6T) and Android 13 (OnePlus 8T).

**Comment by j-kaltes** [comment]
Your timezone has to be GMT-04:00. 
Juggluco 5.1.5 does work with new US Libre 2 sensors. I myself tested a new US Libre 2 sensor with it and I heard of others using it succesfully. The package also didn't contain alcohol pads anymore.  
What is the date on the package? Is it a new or old US Libre 2 sensor? Does it work with the unpatched or patched Libre 2.7.2 app?

**Comment by rahlquist** [comment]
These Do work with the unpatched 2.7.2 app. 
LOT# KTP06682
Date 2024-01-31
FCC ID: QXS-LIB02S
Box REV A 06/22

If you want/need more info from the box or logs let me know. 

Its a bummer I just got 6 sensors. I guess I could switch to the Libre 3 later if the US version of that is working. 

I looked up that FCC ID and it may be a revised unit. I compared to an old sensor I have on hand and there are definite differences in the PCB. The FCC filing the PCB is missing the ceramic antenna shown in the ifixit teardown images of the sensor which my old one also has. https://www.ifixit.com/Teardown/FreeStyle+Libre+2+Sensor+Teardown/137719

**Comment by j-kaltes** [comment]
To find out what is wrong, it would be useful to run a logging version of Juggluco see under Bug report at https://www.juggluco.nl/Juggluco/download.html

The patched US Libre 2.7.2 app can also send glucose values to Juggluco every minute: https://www.juggluco.nl/USLibre2

**Comment by rahlquist** [comment]
Working on getting you logs now. Primary phone is Android 13 if you would like Android 11 logs as well just let me know. 

Log file sent.

**Comment by j-kaltes** [comment]
You are an old user. You should install a debuggable version of Juggluco and remove libcalibrate.so from /data/data/tk.glucodata/files via adb:
`adb shell run-as tk.glucodata rm /data/data/tk.glucodata/files/libcalibrate.so`

**Comment by rahlquist** [comment]
removed the libcalibrate
wiped the old log
rebooted
killed juggluco
read sensor in oem app, force closed after
read sensor in patched app, force closed after
opened juggluco
did two read attempts
exported log and sent via email

**Comment by j-kaltes** [comment]
Did you reinstall Juggluco 5.1.5?

**Comment by rahlquist** [comment]
I had not but after reading this I went ahead and did it wouldn't read. So then I reopened the patched 2.7.2 and did a read force closed it and went back into 5.1.5 and it read it. 

So is it likely my Android 11 device also has that old library that needs to be removed and that's why it wasn't working either? 

Thank you so much for the help.

**Comment by j-kaltes** [comment]
https://drive.google.com/file/d/1yCuq7cEUsAusdiBeEZBJaWaxOl2Vxpbl/view?usp=drive_link removes the library itself.
I should made this change earlier. I once thought about this problem, but didn't do anything because I thought that only a few persons used Juggluco with US Libre 2 sensors for so long and that they would already have tried whether reinstalling Juggluco maybe solved the problem so it didn't matter anymore.

**Comment by AgushkaNightscout** [comment]
I have same issue with L2 RU version sensor. My dia-phone (Cubot Poket, Android 10) can't intercept (already activated with Abbot's original L2 app) L2-RU sensor with NFC, although L3 could activate. But another phone (Realme 10, Android 13) can! I activate sensor with Realme and then transfer the sensor to Cubot using Juggluco's "Get Glucose values on Android device without NFC" option. Why can this happen?
