### ISSUE TITLE
Please consider a changelog

### ISSUE THREAD

**Issue by daik** [j-kaltes/Juggluco#44]
Could you please consider including a changelog in the repository? Just something basic to help communicate what is new in what version.

**Comment by j-kaltes** [comment]
On the [download page](https://www.juggluco.nl/Juggluco/download.html) is a link to https://www.juggluco.nl/Juggluco/changes.html

**Comment by daik** [comment]
Thank you, I've looked for them but clearly  searched for the wrong words, I started in the code and went from there. I think that is enough. I'll close the issue.
