### ISSUE TITLE
Connection errors 133 since June update on Samsung Galaxy A53

### ISSUE THREAD

**Issue by saveheinen** [j-kaltes/Juggluco#46]
Hi,

first i would like to compliment you with this awesome app that i have been using for a while now. It was always pretty solid/stable until i installed the June update from Samsung on my Galaxy A53.

I am wondering if more users have reported this? 

The stream is very unstable since the june update was installed, when lucky it works for a few minutes but now i am at a point where it only receives readings 1 or 2 times. After that, error 133, see screenshots below.

<a href="https://ibb.co/wKQ4kzR"><img src="https://i.ibb.co/y8kq9QX/Screenshot-20230630-115909-Juggluco.jpg" alt="Screenshot-20230630-115909-Juggluco" border="0"></a>

<a href="https://ibb.co/znWYPTF"><img src="https://i.ibb.co/dWsqkwt/Screenshot-20230630-120940-Juggluco.jpg" alt="Screenshot-20230630-120940-Juggluco" border="0"></a>

Some facts:

- there was a sensor active when i installed the update, the sensor was still active after the update and could be scanned using NFC without any problems

- i tried disable/enable bluetooth on my phone, disable/enable "use bluetooth" within the app (from the sensor menu and from the settings menu), rebooted my phone several times, forced a stop of the juggluco app
- i have no Freestyle Libre app on my phone
- battery saving is off for the juggluco app
- i replaced my sensor, didn't help (i'm living in NL and receive my sensors from Mediq Direct Diabetes)

I am glad to help with anything.

**Comment by j-kaltes** [comment]
I don't know. Is there still an Android 13 problem with your phone? 
Did you try whether setting _Android 13_ makes a difference?
Did you turn on "_Allow background activity_" for Juggluco?
Maybe there is still a battery optimization option to turn off.

**Comment by saveheinen** [comment]
Thanks for your quick reply.

Some more info:

- Android 13 checkbox on seems to make the problem worse, so i keep this off
- Wakelock on/off -> no difference
- Turbo on/off -> no difference
- Battery optimization is turned off
- Allow background activity is turned on
- Disabled/enabled "patched libre broadcast" -> no difference

I find it strange that the problems started immediately after the update. I was "hoping" more people are experiencing this.

**Comment by saveheinen** [comment]
Seems more people (at least 1) are experiencing issues with bluetooth devices for diabetic usage after installing the latest update -> https://forum.xda-developers.com/t/samsung-galaxy-a53-reverse-a536bxxu6cwe9-update.4600171/#post-88689603

Unfortunately no answers there (yet). 

Edit 14:17

Some more threads that address BT issues caused by the Samsung June update (a536bxxu6cwe9):

https://eu.community.samsung.com/t5/galaxy-a-serie/a53-probleme-mit-bluetooth-nach-update-erneut/td-p/7686882/page/2
https://eu.community.samsung.com/t5/galaxy-a-serie/a53-bt-problem-libre-3/td-p/7725461
https://eu.community.samsung.com/t5/galaxy-a-serie/probleme-mit-bluetooth-an-der-packstation/m-p/7717551

Sad thing is that Samsung doesn't allow you to rollback this update. They updated the "Bit/SW Rev." value from 5 to 6 and you are only allowed to rollback to a Bit/SW Rev. number that is equal or higher. All previous updates have a lower "Bit/SW Rev." number (5 or lower).

If interested, more info here:

What is this Bit/SW Rev. value? -> https://samfw.com/blog/what-is-bit-binary-value
Overview of all updates and their Bit/SW Rev. value -> https://samfw.com/firmware/SM-A536B/PLS

**Comment by saveheinen** [comment]
Issue seems to be solved by the July update on my Samsung A53

**Comment by saveheinen** [comment]
Solved by Samsung's July update.

**Comment by saveheinen** [comment]
Solved by Samsung's July update.

**Comment by missmah** [comment]
Running into this issue (error 133) today after a Samsung update yesterday on my Galaxy S20+

Does this mean I can't use juggluco on this phone until Samsung hopefully fixes this in a future update? And my sensor is wasted as well? :/

**Comment by j-kaltes** [comment]
When you look at the date of the last post, you see that it was posted at Aug 25, 2023. It is unlikely that you have the same problem.
