### ISSUE TITLE
No connection / Data processing error

### ISSUE THREAD

**Issue by miklosz** [j-kaltes/Juggluco#47]
Hi!
Sarted using juglucco recently, I am on my first sensor (Libre 2 EU). It worked more or less fine for 10 days (so 4 more days left).
Suddenly the connection was lost (status = 133) and also scanning by NFC returns "Data processing error"
Samsung @Android 12, latest update 1 May

What I've tried so far:
- rebooting phone
- turning BT off and on
- turning NFC off and on
- toggle "use bluetooth", "turbo", "Android 13"

Nothing helps.
Where do you store some more logs that I can share?

![357598630_990197865764571_2131061435318832075_n](https://github.com/j-kaltes/Juggluco/assets/1719740/5f29a214-b3f9-4030-9f54-91cf09c8fc6a)

**Comment by j-kaltes** [comment]
Everytime you scan it returnes this error? Can you scan the sensor with the Abbott's Libre 2 app?

**Comment by stephend61** [comment]
I have had the version sold in Australia stop working for up to 2 hours and then just work again, that has happened twice once on the libre app (prior to discovering juglucco ) and once on the juglucco app.

**Comment by miklosz** [comment]
Guess what? It happened again with another sensor, again in 10th day of live. 
My first guess without any deeper investigation is that Juglucco drains the sensor battery much faster then other apps, probably due to too frequent readings

Other apps show (xdrip, FSL patched) show sensor failure

**Comment by j-kaltes** [comment]
And this time again, can you scan the sensor with Abbott's Libre app? If you can't get it from Google Play, you can take this one: https://www.juggluco.nl/USLibre2/
Juggluco doesn't read from the sensor, except by scanning. The sensor sends glucose values every minutes to the app that has enabled that.
I don't believe that the battery of the sensor is ever exhausted.

**Comment by miklosz** [comment]
Using Libre Patched (other version than from your link, because I use EU not US sensors), says more or less "Replace your sensor. This sensor is not working". Scanning directly with NFC in xdrip: "Cannot use this sensor as it's in failure state"

Two different sensors, the same scenario after 10d, might be faulty series, might be that recent sensors are different. 
On the other hand - that never happened when not using Juglucco.

Don't expect much help, it's hard to debug in this situation.
But I might be just the first one to submit this problem here ;-)

What I can suggest is to add an option of less frequent connection to sensor. 
The battery is exhausted at some point. This is the same battery as in Libre 1, which lasted way beyond 14d, but in the end it did run out of power

**Comment by j-kaltes** [comment]
A "_Data processing error_" I only get when an sensor is at least 14 days old. I can't remember having a "_Data processing error_" at any other moment.
You are claiming that a "_Your Sensor is not working. Please remove your Sensor and start a new one._" problem is somehow related to an empty battery and that Juggluco is using the battery more because it would more frequently ask for glucose values than other apps. This is all total nonsense. As I said Juggluco doesn't read glucose values out of the sensor, the sensor sends glucose values. Juggluco connects with the sensor to enable these "_Notifications_".

**Comment by miklosz** [comment]
OK, any other ideas why sensors work only 10 days instead of 14? 
Are you aware of any new limitations from the manufacturer that would I don't know detect unofficial app and "kill" the sensor earlier? 

Of course, it can be still just a faulty sensor series... And most probably it is, so I am closing the issue
