### ISSUE TITLE
No accurate conversion from mg/dl to mmol/l

### ISSUE THREAD

**Issue by pachi81** [j-kaltes/Juggluco#54]
I have detected, that the conversion from the raw value in mg/dl to mmol/l is not accurate.
For example 145 mg/dl will be shown as 8.1 mmol/l, but it should be 8.0 mmol/l.
It seems you are using 18 as divisor, the correct one is 18.0182 or you can use 0.0555 as factor as decribed [here](https://www.mdapp.co/blood-sugar-conversion-calculator-71/).

Regards, Michael

**Comment by j-kaltes** [comment]
Juggluco uses 18 as a conversion factor, just like almost everyone else. Now I see that there really is a glucose value where it makes a difference.

I know there are more numbers:
100: 5.555556 5.549944
109: 6.055556 6.049439
118: 6.555556 6.548934
127: 7.055556 7.048429
136: 7.555556 7.547924
_145: 8.055555 8.047419_
154: 8.555555 8.546914
163: 9.055555 9.046409
172: 9.555555 9.545904
181: 10.055555 10.045399
190: 10.555555 10.544893
199: 11.055555 11.044389
208: 11.555555 11.543883
217: 12.055555 12.043379
226: 12.555555 12.542873
235: 13.055555 13.042368
244: 13.555555 13.541862
253: 14.055555 14.041357
262: 14.555555 14.540854
271: 15.055555 15.040349
280: 15.555555 15.539844
289: 16.055555 16.039339
298: 16.555555 16.538834
300: 16.666668 16.649832
307: 17.055555 17.038328
309: 17.166668 17.149326
316: 17.555555 17.537823
318: 17.666668 17.648823
325: 18.055555 18.037319
327: 18.166668 18.148317
334: 18.555555 18.536814
336: 18.666668 18.647812
343: 19.055555 19.036308
345: 19.166668 19.147306
352: 19.555555 19.535803
354: 19.666668 19.646801
361: 20.055555 20.035297
363: 20.166668 20.146297
370: 20.555555 20.534794
372: 20.666668 20.645792
379: 21.055555 21.034288
381: 21.166668 21.145287
388: 21.555555 21.533783
390: 21.666668 21.644781
397: 22.055555 22.033278
399: 22.166668 22.144276
406: 22.555555 22.532772
408: 22.666668 22.643772
415: 23.055555 23.032269
417: 23.166668 23.143267
424: 23.555555 23.531763
426: 23.666668 23.642761
433: 24.055555 24.031258
435: 24.166668 24.142256
442: 24.555555 24.530752
444: 24.666668 24.641750
451: 25.055555 25.030247
453: 25.166668 25.141247
460: 25.555555 25.529743
462: 25.666666 25.640741
469: 26.055553 26.029236
471: 26.166666 26.140238
478: 26.555553 26.528732
480: 26.666666 26.639730
487: 27.055553 27.028225
489: 27.166666 27.139227
496: 27.555553 27.527721
498: 27.666666 27.638721

**Comment by pachi81** [comment]
Yes, it is not a big difference, but in nightscout or xdrip I have sometimes seen another value, then in Juggluco.

**Comment by j-kaltes** [comment]
When you look at most sites it is the opposite:
https://www.ricktroy.com/blood-glucose-chart-mmol-mg/
https://www.bbraun.co.uk/en/patients/diabetes-care-for-patients/blood-glucose-measurement/conversion-tables.html
https://www.unitsconverters.com/en/Mg/Dl-To-Mmol/L/Utu-4731-4730#formulaDiv
https://www.omnicalculator.com/health/blood-sugar
https://www.diabeteschart.org/mgmmol.html
https://www.nutrisense.io/blog/blood-sugar-conversion-chart#:~:text=1%20mmol%2FL%20of%20blood,L%20value%20of%20blood%20glucose.

The following contains both, one in the table and one as a result of the calculator:
http://www.soc-bdr.org/rds/authors/unit_tables_conversions_and_genetic_dictionaries/conversion_glucose_mg_dl_to_mmol_l/index_en.html

**Comment by j-kaltes** [comment]
https://drive.google.com/file/d/1_dC-rGFnbSkc3LTRPZXMprhvs9C6FpUH/view?usp=drive_link
contains a version that uses 18.0182 instead of 18.
It has the disadvantage that you need to use floating point numbers instead of just 18.
I don't know whether in this modified version numbers are everywhere exactly on whole or half numbers when I meant to do so.
Of the 460 numbers in the sensor range (between 40 and 500 mg/dL), 68 differ 0.1 the rest differ 0.
That is 1 in 7. On my real stream data, 1 in 20 values is different.

**Comment by pachi81** [comment]
Is it such a big disadvantage? The result is also a floating number, so it is only the conversion!?
But I don't know your code.
I'm also fine with 18 as it is not a big thing as you mentioned! I only recognized the small difference, while comparing with nightscout, but it never disturb me!
So if you prefer to let it as it is, I'm fine with!

**Comment by j-kaltes** [comment]
I thought it was an unnecessary precision. It is easier when steps of 18 are exactly one mmol/L.
180.182, somehow become 180.182007 (I use conversion from mg/L):
```
#include <stdio.h>
int main() {
	float get=180.182f;
	printf("%f\n",get);
	}
```
Even when I get rid of this by using double, you get that I can't find a mg/dL number that exactly fits with a whole or half mmol/L number. What mg/dL number should I take for exactly 5 mmol/L?
The following is an update, related to this:
https://drive.google.com/file/d/14NOUX0wqXYTnWWoG-331GssJ9cQ_Nd3k/view?usp=drive_link

**Comment by pachi81** [comment]
As I wrote, using 18 is also ok. This precision is good enough, at least if it causes more problems.
I thought, it is only a small conversion function.
And I think nobody regocnized the small difference or nobody have a problem with.
So we can close this issue, if you like!
