### ISSUE TITLE
no watching and restart watching

### ISSUE THREAD

**Issue by XuefengYang1128** [j-kaltes/Juggluco#76]
Version name: 5.1.8
Sensor: Libre 3
Android: 13

Does the app also take breaks? I have noticed that sometimes it stops updating, and there are no new values. After a few moments, it restarts. For instance, it stopped at 17:00 and restarted at 17:13.

Should I be concerned about the duration when no values are being offered? Is it advisable to initiate a sensor by rescan?

[logcat.txt](https://github.com/j-kaltes/Juggluco/files/12477349/logcat.txt)

**Comment by j-kaltes** [comment]
Normally Juggluco receives nearly all values when the phone is near the sensor. Rescanning Libre 3 is only needed after using the sensor with another app.
Have you disabled all battery optimizations for Juggluco and given it running background permission?
What phone do you use?
What does Left menu->Sensor show?

**Comment by XuefengYang1128** [comment]
Thank you very much. 
I've observed that Juggluco successfully receives data every 5 minutes. However, when I'm away from my phone for an extended period, it doesn't receive data every 1 minute as expected (will lose part of data). Personally, I would prefer to keep the 1-minute interval data.
I've previously disabled all battery optimizations as per the instructions. I've now gone ahead and repeated this step to ensure no changes were made while using the phone.
For running Juggluco, I'm using a Honor V10 phone.
I didn't notice what the sensor show... Could be "no connection", so I rescan the sensor.

**Comment by j-kaltes** [comment]
The Honor V10 contains a Kirin 970 chipset.
I have a Huawei Mediapad m5 tablet containing a Kirin 960s chipset. This tablet has a very bad connection with both Libre 2 and Libre 3 sensors. 
This even though I switch to manually battery->App Launch (turning on Auto-Launch, secondary launch and run in background). Under "More battery settings", I also turned on "Stay connected when device sleeps" .

**Comment by XuefengYang1128** [comment]
![Screenshot_20230830_224105_tk glucodata 1](https://github.com/j-kaltes/Juggluco/assets/122603798/0a302f55-c5f8-4e0c-b3b5-b3a1979c3dc0)

**Comment by XuefengYang1128** [comment]
Thank you so much. Now I see the problem😊

**Comment by XuefengYang1128** [comment]
I have one final question. Could you provide any recommendations for a phone that would work better with Juggluco?

**Comment by j-kaltes** [comment]
My own phone is already 2.5 years old and has good bluetooth: 
It contains the following chipset:
Chipset Qualcomm SM8350 Snapdragon 888 5G (5 nm)
CPU  Octa-core: 1x2.84 GHz Cortex-X1 & 3x2.42 GHz Cortex-A78 & 4x1.80 GHz Cortex-A55

The NFC is worse than my previous phone, but that is not so important.

**Comment by XuefengYang1128** [comment]
Thank you so much😊
