### ISSUE TITLE
Mirror: allow hostname instead of IP

### ISSUE THREAD

**Issue by j42c** [j-kaltes/Juggluco#9]
To deal with changing IPs and DynDNS, it would be great if hostnames were allowed instead of IP addresses.

**Comment by j-kaltes** [comment]
That is now not possible and also not easily changed. You can only use multiple IPs.
Maybe some other solution is possible.
What is exactly your situation?

**Comment by j42c** [comment]
I'm running juggluco-server behind a DSL access to collect the libre3 data. There I have no static public IPv4 address, it changes from time to time. If hostnames can't be used, I think the next best solution would be to use a cloud vm with a static ip for this job or just to forward the connection from there to my DSL access. Or do you have another idea?

**Comment by pachi81** [comment]
What about using a VPN connection, so you can use your local IP from everywhere.

**Comment by j-kaltes** [comment]
Why not add the IP every time it changes (a few seconds work)? It is said that the propagation time of DNS changes can take up to 72 hours (https://ns1.com/resources/dns-propagation), although in my experience it is nearly immediate.

**Comment by j42c** [comment]
Thanks for the suggestions!
